name: Deploy to S3

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Workflow runs on Ubuntu virtual machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checkout code from GitHub repository

      - name: Configure AWS Credentials  # Configure AWS credentials securely
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Update with your S3 bucket region

      # Uncomment and adjust this if you need to build your project before deployment
      # - name: Build Project (if necessary)
      #   run: npm run build  # Adjust based on your project's build command

      - name: Sync Files to S3  # Sync files to the specified S3 bucket
        run: aws s3 sync . s3://cicdbucketmario/ --delete --exclude ".git/*" --exclude ".github/*"  # Replace with your S3 bucket name
